name: Integration Tests
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          - PHP_VERSION: php82-fpm
            MAGENTO_VERSION: 2.4.6
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Docker
        run: docker run --detach -p 8080:80 --name magento-project-community-edition michielgerritsen/magento-project-community-edition:${{ matrix.PHP_VERSION }}-magento${{ matrix.MAGENTO_VERSION }}

      - name: Remove version from composer.json
        run: sed -i '/version/d' ./composer.json

      - name: Install Hyva
        run: |
          docker exec magento-project-community-edition sh -c "mkdir -p ~/.ssh/ && echo \"${{ secrets.SSH_PRIVATE_KEY }}\" > ~/.ssh/id_ed25519"
          docker exec magento-project-community-edition sh -c "chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_ed25519"
          docker exec magento-project-community-edition sh -c "ssh-keyscan -t rsa gitlab.hyva.io >> ~/.ssh/known_hosts"
          docker exec magento-project-community-edition ./retry "composer config repositories.hyva-themes/magento2-theme-module git git@gitlab.hyva.io:hyva-themes/magento2-theme-module.git && composer config repositories.hyva-themes/magento2-reset-theme git git@gitlab.hyva.io:hyva-themes/magento2-reset-theme.git && composer config repositories.hyva-themes/magento2-email-module git git@gitlab.hyva.io:hyva-themes/magento2-email-module.git && composer config repositories.hyva-themes/magento2-default-theme git git@gitlab.hyva.io:hyva-themes/magento2-default-theme.git"
          docker exec magento-project-community-edition ./retry "composer require hyva-themes/magento2-default-theme"
          docker exec magento-project-community-edition ./retry "bin/magento setup:upgrade"
          
          docker exec magento-project-community-edition sh -c "magerun2 dev:theme:list --format=json"
          docker exec magento-project-community-edition sh -c "magerun2 dev:theme:list --format=json | jq -r '.[] | select(.code == \"Hyva\\/default\") | .id'"
          THEME_ID=$(docker exec magento-project-community-edition sh -c "magerun2 dev:theme:list --format=json | jq -r '.[] | select(.code == "Hyva/default") | .id'")
          echo "Hyvä has theme ID $THEME_ID"
          docker exec magento-project-community-edition ./retry "magerun2 config:store:set design/theme/theme_id $THEME_ID --scope=default --scope-id=0 && magerun2 config:store:set design/theme/theme_id $THEME_ID --scope=stores --scope-id=1"

      - name: Upload the code into the docker container
        run: |
          docker cp $(pwd) magento-project-community-edition:/data/extensions/
          docker exec magento-project-community-edition sh -c "jq '. + {replace: {\"magewirephp/magewire\": \"1.99.0\"}}' composer.json > temp.json && mv temp.json composer.json"
          docker exec magento-project-community-edition composer require --no-plugins --no-interaction magewirephp/magewire:@dev
          docker exec magento-project-community-edition composer require --no-plugins --no-interaction magewirephp/magewire-examples:@dev

      - name: Check webserver
        run: curl --fail-with-body -vvv http://localhost:8080