name: Integration Tests
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          - PHP_VERSION: php82-fpm
            MAGENTO_VERSION: 2.4.6
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Docker
        run: docker run --detach --name magento-project-community-edition michielgerritsen/magento-project-community-edition:${{ matrix.PHP_VERSION }}-magento${{ matrix.MAGENTO_VERSION }}

      - name: Remove version from composer.json
        run: sed -i '/version/d' ./composer.json

      - name: Install Hyva
        run: |
          docker exec magento-project-community-edition sh -c "mkdir -p ~/.ssh/ && echo \"${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519"
          docker exec magento-project-community-edition "ssh-keyscan -t rsa gitlab.hyva.io >> ~/.ssh/known_hosts"
          docker exec magento-project-community-edition ./retry "composer config repositories.hyva-themes/magento2-theme-module git git@gitlab.hyva.io:hyva-themes/magento2-theme-module.git && composer config repositories.hyva-themes/magento2-reset-theme git git@gitlab.hyva.io:hyva-themes/magento2-reset-theme.git && composer config repositories.hyva-themes/magento2-email-module git git@gitlab.hyva.io:hyva-themes/magento2-email-module.git && composer config repositories.hyva-themes/magento2-default-theme git git@gitlab.hyva.io:hyva-themes/magento2-default-theme.git && composer config repositories.hyva-themes/hyva-checkout git git@gitlab.hyva.io:hyva-checkout/checkout.git"
          docker exec magento-project-community-edition ./retry "composer require hyva-themes/magento2-default-theme hyva-themes/magento2-hyva-checkout"
          docker exec magento-project-community-edition ./retry "bin/magento setup:upgrade"
          docker exec magento-project-community-edition ./retry "magerun2 config:store:set design/theme/theme_id 3 --scope=default --scope-id=0 && magerun2 config:store:set design/theme/theme_id 5 --scope=stores --scope-id=1"
          docker exec magento-project-community-edition ./retry "bin/magento config:set general/region/display_all 0 && bin/magento config:set hyva_themes_checkout/general/checkout default"